Global:
  use_gpu: False
  epoch_num: 1
  log_smooth_window: 20
  print_batch_step: 1
  save_model_dir: /Users/dmitry/PaddleOCR/train_res_sdmgr
  save_epoch_step: 50
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [ 0, 1 ]
  # 1. If pretrained_model is saved in static mode, such as classification pretrained model
  #    from static branch, load_static_weights must be set as True.
  # 2. If you want to finetune the pretrained models we provide in the docs,
  #    you should set load_static_weights as False.
  load_static_weights: False
  cal_metric_during_train: False
  pretrained_model: 
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  class_path: &class_path /Users/dmitry/PaddleOCR/train_data/class_list.txt
  infer_img:
  save_res_path:
  img_scale: [ 1024, 512 ]

Architecture:
  model_type: kie
  algorithm: SDMGR
  Transform:
  Backbone:
    name: Kie_backbone
  Head:
    name: SDMGRHead

Loss:
  name: SDMGRLoss

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    learning_rate: 0.001
    decay_epochs: [ 60, 80, 100]
    values: [ 0.001, 0.0001, 0.00001]
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    factor: 0.00005

PostProcess:
  name: None

Metric:
  name: KIEMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /Users/dmitry/PaddleOCR/dataset_cr/dataset_processed/images
    label_file_list: [ '/Users/dmitry/PaddleOCR/dataset_cr/dataset_processed/train.txt' ]
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - NormalizeImage:
          scale: 1
          mean: [202.99014282226562, 201.5799560546875, 203.59658813476562]
          std: [53.26708984375, 57.00006866455078, 60.91695022583008]
          order: 'hwc'
      - KieLabelEncode: # Class handling label
          character_dict_path: /Users/dmitry/PaddleOCR/train_data/dict_tw_ru_doc.txt
          class_path: *class_path
      - KieResize:
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'relations', 'texts', 'points', 'labels', 'tag', 'shape'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 1
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /Users/dmitry/PaddleOCR/dataset_cr/dataset_processed/images
    label_file_list:
      - /Users/dmitry/PaddleOCR/dataset_cr/dataset_processed/test.txt
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - KieLabelEncode: # Class handling label
          character_dict_path: /Users/dmitry/PaddleOCR/train_data/dict_tw_ru_doc.txt
      - KieResize:
      - NormalizeImage:
          scale: 1
          mean: [202.99014282226562, 201.5799560546875, 203.59658813476562]
          std: [53.26708984375, 57.00006866455078, 60.91695022583008]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'relations', 'texts', 'points', 'labels', 'tag', 'ori_image', 'ori_boxes', 'shape']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 4
